import { Foods } from './foods.model';

export const FOODS: Foods[] = [
  {name: 'Alcoholic spirit(s)', isEnabled: true},
  {name: 'Bacon', isEnabled: true},
  {name: 'Bagels', isEnabled: true},
  {name: 'Beer', isEnabled: true},
  {name: 'Burrito', isEnabled: true},
  {name: 'Cake', isEnabled: true},
  {name: 'Pasta', isEnabled: true},
  {name: 'Pistachios', isEnabled: true},
  {name: 'Corn', isEnabled: true},
  {name: 'Mushrooms', isEnabled: true},
  {name: 'Pumpkin Seeds', isEnabled: true},
  {name: 'Green Salad', isEnabled: true},
  {name: 'Broccoli', isEnabled: true},
  {name: 'Olive Oil (Extra Virgin)', isEnabled: true},
  {name: 'Olive(s)', isEnabled: true},
  {name: 'Cheddar Cheese (Low Fat)', isEnabled: true},
  {name: 'Avocado(s)', isEnabled: true},
  {name: 'Whole Wheat Tortilla(s)', isEnabled: true},
  {name: 'Whole Wheat Bread', isEnabled: true},
  {name: 'Fat Free Greek Yogurt', isEnabled: true},
  {name: 'Black Beans (Cooked)', isEnabled: true},
  {name: 'Whole Wheat Pasta (Cooked)', isEnabled: true},
  {name: 'Couscous (Cooked)', isEnabled: true},
  {name: 'Baked Potato(es)', isEnabled: true},
  {name: 'Ground Beef (93-97% Lean)', isEnabled: true},
  {name: 'Top Sirloin Steak (Fat Trimmed)', isEnabled: true},
  {name: 'Shrimp(s)', isEnabled: true},
  {name: 'Tuna (Skinless)', isEnabled: true},
  {name: 'Salmon (Skinless)', isEnabled: true},
  {name: 'Haddock (Skinless)', isEnabled: true},
  {name: 'Chicken Breast(s) (Skinless, Boneless)', isEnabled: true},
  {name: 'Peanut Butter (Reduced Sodium)', isEnabled: true},
  {name: 'Cheddar Cheese (Low Fat)', isEnabled: true},
  {name: 'Whole Wheat Tortilla(s)', isEnabled: true},
  {name: 'Whole Wheat Bread', isEnabled: true},
  {name: 'Oat or Bran Cereal (Plain)', isEnabled: true},
  {name: 'Granola (Reduced Sugar, Plain)', isEnabled: true},
  {name: 'Egg Whites', isEnabled: true},
  {name: 'Protein Shake', isEnabled: true},
  {name: 'Skimmed Milk (1% Fat)', isEnabled: true},
  {name: 'Pizza Slices', isEnabled: true},
  {name: 'Hot dog(s)', isEnabled: true},
  {name: 'Ice Cream', isEnabled: true},
  {name: 'French fries', isEnabled: true},
  {name: 'Cheese Burger', isEnabled: true},
  {name: 'Fish and Chips', isEnabled: true},
]
